#!/bin/bash
# Script 5: Open Source Manifesto Generator
# Author: [Shital Das] | Reg No: [24BCE11286]
# Course: Open Source Software
# Description: Asks the user 3 questions and generates a personal
#              open source philosophy statement, saved to a .txt file

# ─────────────────────────────────────────
# ALIAS CONCEPT (demonstrated via comment)
# In a real shell session you could type:
#   alias manifesto='./script5.sh'
# Then just type 'manifesto' to run this script
# Aliases make long commands shorter and easier to remember
# ─────────────────────────────────────────

echo "=================================================="
echo "    OPEN SOURCE MANIFESTO GENERATOR              "
echo "=================================================="
echo ""
echo "  Answer three questions to generate your"
echo "  personal open source philosophy statement."
echo ""

# ─────────────────────────────────────────
# USER INPUT — read command asks user to type something
# -p shows a prompt message before waiting for input
# The answer is stored in the variable after the prompt
# ─────────────────────────────────────────
read -p "  1. Name one open-source tool you use every day: " TOOL
echo ""
read -p "  2. In one word, what does 'freedom' mean to you? " FREEDOM
echo ""
read -p "  3. Name one thing you would build and share freely: " BUILD
echo ""

# ─────────────────────────────────────────
# VARIABLES — store date and output filename
# date command gets today's date in a readable format
# whoami gets the current username for the filename
# ─────────────────────────────────────────
DATE=$(date '+%d %B %Y')
TIME=$(date '+%H:%M:%S')
OUTPUT="manifesto_$(whoami).txt"

# ─────────────────────────────────────────
# WRITE TO FILE — using > to create file and >> to append
# > overwrites the file (used for the first line)
# >> appends to the file (used for every line after)
# ─────────────────────────────────────────

# Create the file (or overwrite if it exists) with the title
echo "=================================================" > "$OUTPUT"
echo "        MY OPEN SOURCE MANIFESTO                " >> "$OUTPUT"
echo "=================================================" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "  Generated by : $(whoami)"                        >> "$OUTPUT"
echo "  Date         : $DATE at $TIME"                   >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "-------------------------------------------------" >> "$OUTPUT"
echo "" >> "$OUTPUT"

# ─────────────────────────────────────────
# STRING CONCATENATION — building a paragraph by combining variables
# The variables $TOOL, $FREEDOM, $BUILD are inserted into the text
# ─────────────────────────────────────────
echo "  I believe in the power of open source software." >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "  Every day, I rely on $TOOL — a tool built not" >> "$OUTPUT"
echo "  by a single company seeking profit, but by a"   >> "$OUTPUT"
echo "  community of people who believed that knowledge" >> "$OUTPUT"
echo "  and technology should be shared freely."         >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "  To me, freedom means $FREEDOM. In the world of" >> "$OUTPUT"
echo "  software, that freedom is not just an ideal —"   >> "$OUTPUT"
echo "  it is a license, a philosophy, and a promise"    >> "$OUTPUT"
echo "  written into every line of open source code."    >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "  One day, I hope to build $BUILD and release it"  >> "$OUTPUT"
echo "  to the world under an open license — so that"    >> "$OUTPUT"
echo "  others may learn from it, improve it, and build" >> "$OUTPUT"
echo "  something even greater upon it."                 >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "  That is what standing on the shoulders of"       >> "$OUTPUT"
echo "  giants truly means."                             >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "-------------------------------------------------" >> "$OUTPUT"
echo "  'Free as in freedom, not just free as in beer.'" >> "$OUTPUT"
echo "              — Richard Stallman"                  >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "=================================================" >> "$OUTPUT"

# ─────────────────────────────────────────
# DISPLAY — show success message and print the file
# ─────────────────────────────────────────
echo ""
echo "  ✔ Manifesto saved to: $OUTPUT"
echo ""
echo "=================================================="
echo "  YOUR MANIFESTO:"
echo "=================================================="
echo ""

# cat reads and prints the file contents to the screen
cat "$OUTPUT"
